theme: jekyll-theme-minimal
name: Mehdi S. M. Sajjadi
title: Mehdi S. M. Sajjadi
# description: Personal website of Mehdi S. M. Sajjadi.
logo: https://raw.githubusercontent.com/msmsajjadi/pic/master/pic.jpg
